steps:
  
- id: 'Install node_modules'
  name: 'gcr.io/cloud-builders/yarn'
  dir: 'frontend'
  args: [ 'install' ]

- id: 'Build'
  name: 'gcr.io/cloud-builders/yarn'
  dir: 'frontend'
  args: [ 'build' ]

- id: 'Test'
  name: 'gcr.io/cloud-builders/yarn'
  dir: 'frontend'
  args: [ 'test' ]
  env:
  - 'CI=true'

- id: 'Build image'
  name: 'gcr.io/cloud-builders/docker'
  dir: 'frontend'
  args: [ 
    'build', 
    '-t', 
    'gcr.io/$PROJECT_ID/frontend-prod:${TAG_NAME}', 
    '-t',
    'gcr.io/$PROJECT_ID/frontend-prod:latest', 
    '.' ]

# [Push start]
- id: 'Push tagged image'
  name: 'gcr.io/cloud-builders/docker'
  dir: 'frontend'
  args: [
    'push', 
    'gcr.io/$PROJECT_ID/frontend-prod:${TAG_NAME}']
  
- id: 'Push latest image'
  name: 'gcr.io/cloud-builders/docker'
  dir: 'frontend'
  args: [
    'push', 
    'gcr.io/$PROJECT_ID/frontend-prod:latest']
# [Push end]