apiVersion: skaffold/v1beta8
kind: Config
build:
  artifacts:
  - image: simple-webapp
    context: simple-webapp
  - image: worker
    context: worker
deploy:
  kubectl:
    manifests:
    - k8s/pubsub-claim0-persistentvolumeclaim.yaml
    - k8s/pubsub-deployment.yaml
    - k8s/pubsub-service.yaml
    - k8s/simple-webapp-claim0-persistentvolumeclaim.yaml
    - k8s/simple-webapp-deployment.yaml
    - k8s/simple-webapp-service.yaml
    - k8s/worker-claim0-persistentvolumeclaim.yaml
    - k8s/worker-deployment.yaml
    - k8s/worker-service.yaml
