apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: pubsub
  name: pubsub
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pubsub
    spec:
      containers:
      - args:
        - /bin/bash
        - -c
        - gcloud config set project emulator && gcloud beta emulators pubsub start
          --data-dir /mnt/data/pubsub --host-port 0.0.0.0:8538
        image: google/cloud-sdk:latest
        name: pubsub
        ports:
        - containerPort: 8538
        resources: {}
        volumeMounts:
        - mountPath: /mnt/data/pubsub
          name: pubsub-claim0
      restartPolicy: Always
      volumes:
      - name: pubsub-claim0
        persistentVolumeClaim:
          claimName: pubsub-claim0
status: {}
