apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: simple-webapp
  name: simple-webapp
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: simple-webapp
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: PUBSUB_EMULATOR_HOST
          value: pubsub:8538
        - name: PUBSUB_PROJECT_ID
          value: test
        image: simple-webapp
        name: simple-webapp
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
