steps:
  
- id: 'Install node_modules'
  name: 'gcr.io/cloud-builders/yarn'
  dir: 'simple-webapp/client'
  args: [ 'install' ]

- id: 'Build'
  name: 'gcr.io/cloud-builders/yarn'
  dir: 'simple-webapp/client'
  args: [ 'build' ]

- id: 'Test front'
  name: 'gcr.io/cloud-builders/yarn'
  dir: 'simple-webapp/client'
  args: [ 'test' ]
  env:
  - 'CI=true'

- id: 'Build image'
  name: 'gcr.io/cloud-builders/docker'
  dir: 'simple-webapp'
  args: [ 
    'build', 
    '-t', 
    'gcr.io/$PROJECT_ID/simple-webapp-prod:${TAG_NAME}', 
    '-t',
    'gcr.io/$PROJECT_ID/simple-webapp-prod:latest', 
    '.' ]

- id: 'Push tagged image'
  name: 'gcr.io/cloud-builders/docker'
  dir: 'simple-webapp'
  args: [
    'push', 
    'gcr.io/$PROJECT_ID/simple-webapp-prod:${TAG_NAME}']
  
- id: 'Push latest image'
  name: 'gcr.io/cloud-builders/docker'
  dir: 'simple-webapp'
  args: [
    'push', 
    'gcr.io/$PROJECT_ID/simple-webapp-prod:latest']
