steps:

- id: 'Build image'
  name: 'gcr.io/cloud-builders/docker'
  dir: 'worker'
  args: [ 
    'build', 
    '-t', 
    'gcr.io/$PROJECT_ID/worker-prod:${TAG_NAME}', 
    '-t',
    'gcr.io/$PROJECT_ID/worker-prod:latest', 
    '.' ]

- id: 'Push tagged image'
  name: 'gcr.io/cloud-builders/docker'
  dir: 'worker'
  args: [
    'push', 
    'gcr.io/$PROJECT_ID/worker-prod:${TAG_NAME}']
  
- id: 'Push latest image'
  name: 'gcr.io/cloud-builders/docker'
  dir: 'worker'
  args: [
    'push', 
    'gcr.io/$PROJECT_ID/worker-prod:latest']

- id: 'Deploy on cloud run'
  name: 'gcr.io/cloud-builders/gcloud'
  dir: 'worker'
  args: [
    'beta', 
    'run', 
    'deploy', 'worker-prod',
    '--image', 'gcr.io/$PROJECT_ID/worker-prod:${TAG_NAME}', 
    '--region', 'us-central1']
